### ISSUE TITLE
User landing page - Start or Continue (page serving)

### ISSUE THREAD

**Issue by karimbahgat** [wmgeolab/scope#10]
## Before you begin:
Make sure you understand how Django views work:
  - https://docs.djangoproject.com/en/3.1/topics/http/views/
  - https://docs.djangoproject.com/en/3.1/intro/tutorial03/
  
Also read up on Django urls:
  - https://docs.djangoproject.com/en/3.1/topics/http/urls/.

And understand how to read from and write to the database:
  - https://docs.djangoproject.com/en/3.1/topics/db/queries/
  - https://docs.djangoproject.com/en/3.1/topics/db/examples/many_to_one/

## Template information
- Path to template file: `templates/parsing/landing.html`
- Context variables:
  - `continue_event` (type: parsing.models.Activity)
     Acitivity model instance if user already has an event checked out, otherwise None

## Tasks for `views.py`:
- [x] Create page view function `landing()`:
  - [x] Get the Activity model instance if user already has an event checked out, store in `continue_event` variable. See #11 for how this is stored. 
  - [x] Render to template. 

## Tasks for `urls.py`:
- [x] Add `views.landing` to list of urlpatterns:
  - URL pattern: 'landing/'
  - name: 'landing'

**Comment by karimbahgat** [comment]
I unticked the subtask that retrieves the current user event, now that we know how to store the user event.

**Comment by karimbahgat** [comment]
@KateMunkacsy I see you ticked off the final subtask, but don't see a corresponding commit. Can I close the issue or are you still working on it?

**Comment by KateMunkacsy** [comment]
@karimbahgat This issue should be all done - It looks like the code on here has all my changes.  The relevant commit for that last adjustment that needed to be made is called 'Adjust Activity Model Instance' on the parsing/views.py

**Comment by karimbahgat** [comment]
Ok, I see it now. Upon review however, with `Activity.objects.get(pk=current_user)` you're comparing the id of a user (`current_user`) with the id of an activity (`pk`). What we actually want is to lookup and match on the field that stores the activity's current user (the Activity model's `current_user` field), ie `Activity.objects.get(current_user=current_user)`. I went ahead and fixed it.
