### ISSUE TITLE
How to store which user has checked out an Activity

### ISSUE THREAD

**Issue by karimbahgat** [wmgeolab/scope#11]
## Description
User can only checkout one activity at a time. 
Store this as a onetoonefield on activity model that links to a single user and where the user must be unique. 

## Before you begin:
Make sure you understand how Django models and fields work:
  - https://docs.djangoproject.com/en/3.1/topics/db/models/
  - https://docs.djangoproject.com/en/3.1/ref/models/fields/
  
Be aware of how to link models:
  - https://docs.djangoproject.com/en/3.1/topics/db/examples/many_to_one/
  - https://docs.djangoproject.com/en/3.1/topics/db/examples/many_to_many/

## App folder
This issue pertains to the files contained in the website app folder: 
- `scope_2gzm/parsing`. 

## Tasks for `models.py`:
- [x] Alter model class `Activity`:
  - [x] Add new optional field: `current_user` (type OneToOneField, null=True)

## Tasks if a model has been altered:
NOTE: Only include this section if an existing model has been altered (model renamed, or fields renamed, dropped, or changed):
- [ ] Find and update all references to the altered model **across all** website apps `views.py` files.

## Tasks to sync changes to the database
Example:
- [x] In the commandline, do `python manage.py makemigrations`
- [x] Then `python manage.py migrate`

**Comment by karimbahgat** [comment]
@lclime812 let me know if you have questions about the 3rd subtask, there may or may not be anything that needs to be updated, since the only change is you're adding a new field. In fact, you can probably skip it.

**Comment by lclime812** [comment]
@karimbahgat I keep receiving these two errors when I try to run `python manage.py makemigrations`:
`MySQLdb._exceptions.OperationalError: (1045, "Access denied for user 'landonclime'@'localhost' (using password: NO)")`
`django.db.utils.OperationalError: (1045, "Access denied for user 'landonclime'@'localhost' (using password: NO)")`
Thanks for the help!

**Comment by karimbahgat** [comment]
Did you follow the "Setup" steps in https://github.com/wmgeolab/scope/blob/master/scope_2gzm/README.md , specifically step 5? Write me on slack @ Karim Bahgat, and I can send you the file you need. Matt or Kate should also have the file if it's easier to contact them.

**Comment by karimbahgat** [comment]
@lclime812 could you push your code changes to GitHub (including what you tried to do but didn't work)? Then I can try to fix the issue on my end.

**Comment by karimbahgat** [comment]
I just did makemigrations and migrate and it worked. @lclime812 could you describe what you tried to do and what error message you got? Were you able to get past the previous makemigrations issue or was it some new error?

**Comment by lclime812** [comment]
Unfortunately, it is still the same error I mentioned above. It has been that one this whole time

**Comment by karimbahgat** [comment]
Ok, can you confirm the following:
1. is the db config file in ‘scope/scope_2gzm/db_config.cnf’? 
2. do you have all the python installations in ‘requirements.dev.txt’?

**Comment by lclime812** [comment]
I can confirm those

**Comment by karimbahgat** [comment]
Looks like someone else had the exact same issue: https://stackoverflow.com/questions/45818506/mysql-configuration-for-django

Based on the answers there, maybe the issue is that for some reason the relative path to the config file doesn't work in your environment / it's unable to find it and falls back on your local username. So the solution being changing to absolute path in the database section of `settings.py`: 

```
'read_default_file': os.path.join(BASE_DIR, 'db_config.cnf'),
```

Let me know if that does anything.

**Comment by karimbahgat** [comment]
For the purpose of documentation, the above solution fixed the issue.
