### ISSUE TITLE
Rename Activity model to 'Event'

### ISSUE THREAD

**Issue by karimbahgat** [wmgeolab/scope#12]
## Description
Rename Activity model to 'Event'. 
NOTE: Wait to do this issue until #11 is done. 

## Before you begin:
Make sure you understand how Django models and fields work:
  - https://docs.djangoproject.com/en/3.1/topics/db/models/
  - https://docs.djangoproject.com/en/3.1/ref/models/fields/
  
Be aware of how to link models:
  - https://docs.djangoproject.com/en/3.1/topics/db/examples/many_to_one/
  - https://docs.djangoproject.com/en/3.1/topics/db/examples/many_to_many/

## App folder
This issue pertains to the files contained in the website app folder: 
- `scope_2gzm/parsing`. 

## Tasks for `models.py`:
- [ ] Rename model class `Activity` to `Event`:

## Tasks if a model has been altered:
NOTE: Only include this section if an existing model has been altered (model renamed, or fields renamed, dropped, or changed):
- [ ] Find and update all references to the altered model **across all** website apps `views.py` files.
- [ ] Find and update all models that link to the altered model **across all** website apps `models.py` files.

## Tasks to sync changes to the database
Example:
- [ ] In the commandline, do `python manage.py makemigrations`
- [ ] Then `python manage.py migrate`
