### ISSUE TITLE
Activity list page logic

### ISSUE THREAD

**Issue by karimbahgat** [wmgeolab/scope#16]
## Before you begin:
Make sure you understand how Django views work:
  - https://docs.djangoproject.com/en/3.1/topics/http/views/
  - https://docs.djangoproject.com/en/3.1/intro/tutorial03/
  
Also read up on Django urls:
  - https://docs.djangoproject.com/en/3.1/topics/http/urls/.

And understand how to read from and write to the database:
  - https://docs.djangoproject.com/en/3.1/topics/db/queries/
  - https://docs.djangoproject.com/en/3.1/topics/db/examples/many_to_one/

## App folder
This issue pertains to the files contained in the website app folder: 
- `scope_2gzm/parsing`. 

## Tasks for `views.py`:
- [x] Create page view function `activity_list()`:
  - [x] Get all activities that are not checked out (`current_user` = None).
  - [x] Render to template.

## Render to template
- Path to template file: `templates/parsing/activity_list.html`
- Context variables:
  - `activities` (type: QuerySet)
     Queryset of all activities not currently checked out by a user. 

## Tasks for `urls.py`:
- [x] Add `activity_list()` to list of urlpatterns:
  - URL pattern: 'activity/list'
  - name: 'activity_list'
