### ISSUE TITLE
Activity list page rendering

### ISSUE THREAD

**Issue by karimbahgat** [wmgeolab/scope#17]
## Before you begin:
Make sure you understand how Django templates work:
  - https://docs.djangoproject.com/en/3.1/topics/templates/.
  - https://docs.djangoproject.com/en/3.1/ref/templates/language/
  - https://docs.djangoproject.com/en/3.1/ref/templates/builtins/
  
If the issue involves user input forms, also read up on Django forms:
  - https://docs.djangoproject.com/en/3.1/topics/forms/
  - https://docs.djangoproject.com/en/3.1/ref/forms/fields/

## App folder
This issue pertains to the files contained in the website app folder: 
- `scope_2gzm/parsing`. 

## Template context variables:
- `activities` (type: QuerySet)
     Queryset of all [Activity model instances](https://github.com/wmgeolab/scope/blob/13cc7e90a61baa0c24831614959e186647abef57/scope_2gzm/parsing/models.py#L43) not currently checked out by a user. 

## Tasks for `forms.py`:
None

## Tasks for template html file(s):
- [x] Create file `templates/parsing/activity_list.html`
  - [x] Table of all activities not currently checked out.
  - [x] Each row displays key attributes of an activity.
  - [x] Each row has an 'a href' 'Checkout' button to the right linking to the url name = 'activity_checkout'.

### `PAGE_NAME.html`
```
{% extends "templates/base.html" %}
{% load static %}

{% block page_content %}

PAGE CONTENT GOES HERE

{% endblock %}
```

**Comment by karimbahgat** [comment]
@micrittenden I reviewed your commit, and added a few comments to specific lines of things that need to be fixed. You can close the issue again once you are done.

**Comment by micrittenden** [comment]
resolved edits
