### ISSUE TITLE
Activity release page redirect

### ISSUE THREAD

**Issue by karimbahgat** [wmgeolab/scope#18]
## Before you begin:
Make sure you understand how Django views work:
  - https://docs.djangoproject.com/en/3.1/topics/http/views/
  - https://docs.djangoproject.com/en/3.1/intro/tutorial03/
  
Also read up on Django urls:
  - https://docs.djangoproject.com/en/3.1/topics/http/urls/.

And understand how to read from and write to the database:
  - https://docs.djangoproject.com/en/3.1/topics/db/queries/
  - https://docs.djangoproject.com/en/3.1/topics/db/examples/many_to_one/

## App folder
This issue pertains to the files contained in the website app folder: 
- `scope_2gzm/parsing`. 

## Template information
None

## Tasks for `views.py`:
- [x] Create page view function `activity_release(request, pk)', where pk is the activity id:
  - [x] Get activity
  - [x] Set activity.current_user to None
  - [x] Return `redirect()` to url name = 'activity_list'

## Tasks for `urls.py`:
- [x] Add `activity_release` function to list of urlpatterns:
  - URL pattern: 'activity/(?P<pk>[\w]+)/release'
  - name: 'activity_release'
