### ISSUE TITLE
Activity editing page rendering

### ISSUE THREAD

**Issue by karimbahgat** [wmgeolab/scope#19]
## Before you begin:
Make sure you understand how Django templates work:
  - https://docs.djangoproject.com/en/3.1/topics/templates/.
  - https://docs.djangoproject.com/en/3.1/ref/templates/language/
  - https://docs.djangoproject.com/en/3.1/ref/templates/builtins/
  
If the issue involves user input forms, also read up on Django forms:
  - https://docs.djangoproject.com/en/3.1/topics/forms/
  - https://docs.djangoproject.com/en/3.1/ref/forms/fields/

## App folder
This issue pertains to the files contained in the website app folder: 
- `scope_2gzm/parsing`. 

## Template context variables:
- `form` (type: ActivityForm)
  Model form of the activity being edited.

## Tasks for `forms.py`:
None, ActivityForm already exists. 

## Tasks for template html file(s):
- [x] Create file `templates/parsing/activity_edit.html`
  - [x] Render the `form`
  - [x] Target of the form is url name = 'activity_edit'
  - [x] Form button to submit the form. 
  - [x] Another 'a href' button to release the activity with url name = 'activity_release'

### `PAGE_NAME.html`
```
{% extends "templates/base.html" %}
{% load static %}

{% block page_content %}

PAGE CONTENT GOES HERE

{% endblock %}
```

**Comment by karimbahgat** [comment]
@micrittenden I reviewed your commit, and added a few comments to specific lines of things that need to be fixed. You can close the issue again once you are done.

**Comment by micrittenden** [comment]
Resolved edits
