### ISSUE TITLE
Activity editing page logic

### ISSUE THREAD

**Issue by karimbahgat** [wmgeolab/scope#20]
## Before you begin:
Make sure you understand how Django views work:
  - https://docs.djangoproject.com/en/3.1/topics/http/views/
  - https://docs.djangoproject.com/en/3.1/intro/tutorial03/
  
Also read up on Django urls:
  - https://docs.djangoproject.com/en/3.1/topics/http/urls/.

And understand how to read from and write to the database:
  - https://docs.djangoproject.com/en/3.1/topics/db/queries/
  - https://docs.djangoproject.com/en/3.1/topics/db/examples/many_to_one/

## App folder
This issue pertains to the files contained in the website app folder: 
- `scope_2gzm/parsing`. 

## Tasks for `views.py`:
- [x] Create page view function `activity_edit(pk)`:
  - [x] If method = GET
    - [x] Get the activity.
    - [x] Create ActivityForm with instance=activity
    - [x] Render to template
  - [x] If method = POST
    - [x] Create ActivityForm with POST data
    - [x] Validate and save the form
    - [x] Redirect to url name = 'activity_release'

## Render to template
- Path to template file: `templates/parsing/activity_edit.html`
- Context variables:
  - `form` (type: ActivityForm)
     Model form of activity being edited.

## Tasks for `urls.py`:
- [x] Add `activity_edit(request, pk)` to list of urlpatterns:
  - URL pattern: 'activity/(?P<pk>[\w]+)/edit'
  - name: 'activity_edit'
