### ISSUE TITLE
Create Extract model

### ISSUE THREAD

**Issue by karimbahgat** [wmgeolab/scope#23]
## Description
Create the Extract data model which is linked to the Source model and contains some text relevant for an event. 

## Before you begin:
Make sure you understand how Django models and fields work:
  - https://docs.djangoproject.com/en/3.1/topics/db/models/
  - https://docs.djangoproject.com/en/3.1/ref/models/fields/
  
Be aware of how to link models:
  - https://docs.djangoproject.com/en/3.1/topics/db/examples/many_to_one/
  - https://docs.djangoproject.com/en/3.1/topics/db/examples/many_to_many/

## App folder
This issue pertains to the files contained in the website app folder: 
- `scope_2gzm/extracts`. 

## Tasks for `models.py`:
- [x] Create model class `Extract`:
  - [x] source (type: ForeignKey)
  - [x] text (type: TextField)

## Tasks to sync changes to the database
Example:
- [x] In the commandline, do `python manage.py makemigrations`
- [x] Then `python manage.py migrate`
