### ISSUE TITLE
Extracts home page logic

### ISSUE THREAD

**Issue by karimbahgat** [wmgeolab/scope#25]
## Before you begin:
Make sure you understand how Django views work:
  - https://docs.djangoproject.com/en/3.1/topics/http/views/
  - https://docs.djangoproject.com/en/3.1/intro/tutorial03/
  
Also read up on Django urls:
  - https://docs.djangoproject.com/en/3.1/topics/http/urls/.

And understand how to read from and write to the database:
  - https://docs.djangoproject.com/en/3.1/topics/db/queries/
  - https://docs.djangoproject.com/en/3.1/topics/db/examples/many_to_one/

## App folder
This issue pertains to the files contained in the website app folder: 
- `scope_2gzm/extracts`. 

## Tasks for `views.py`:
- [x] Create page view function `home(requests)`:
  - [x] Get the Source model instance if user already has an event checked out, store in `continue` variable. See #23 for how this is stored. 
  - [x] Render to template. 

## Render to template
- Path to template file: `templates/extracts/home.html`
- Context variables:
  - `continue` (type: sources.models.Source)
     Source model instance if user already has a source checked out, otherwise None

## Tasks for `urls.py`:
- [x] Add `views.home` to list of urlpatterns:
  - URL pattern: 'extracts/home'
  - name: 'extracts_home'
