### ISSUE TITLE
How to store which user has checked out a source

### ISSUE THREAD

**Issue by karimbahgat** [wmgeolab/scope#26]
## Description
Short description of what to do in this task. 

## Before you begin:
Make sure you understand how Django models and fields work:
  - https://docs.djangoproject.com/en/3.1/topics/db/models/
  - https://docs.djangoproject.com/en/3.1/ref/models/fields/
  
Be aware of how to link models:
  - https://docs.djangoproject.com/en/3.1/topics/db/examples/many_to_one/
  - https://docs.djangoproject.com/en/3.1/topics/db/examples/many_to_many/

## App folder
This issue pertains to the files contained in the website app folder: 
- `scope_2gzm/extracts`. 

## Tasks for `models.py`:
- [x] Alter model class `Source`:
  - [x] Add new optional field: `current_user` (type OneToOneField, null=True)

## Tasks if a model has been altered:
None

## Tasks to sync changes to the database
Example:
- [x] In the commandline, do `python manage.py makemigrations`
- [x] Then `python manage.py migrate`

**Comment by lclime812** [comment]
When you say 'Alter model class Source', do you mean alter the model in the modSourcing folder or there should be a Source model in the modExtract folder and alter it, because there is no Source model in modExtract?

**Comment by karimbahgat** [comment]
Hey, that’s correct, the Source model in modSourcing, i should have specified.
