### ISSUE TITLE
Extracts source checkout page redirect

### ISSUE THREAD

**Issue by karimbahgat** [wmgeolab/scope#27]
## Before you begin:
Make sure you understand how Django views work:
  - https://docs.djangoproject.com/en/3.1/topics/http/views/
  - https://docs.djangoproject.com/en/3.1/intro/tutorial03/
  
Also read up on Django urls:
  - https://docs.djangoproject.com/en/3.1/topics/http/urls/.

And understand how to read from and write to the database:
  - https://docs.djangoproject.com/en/3.1/topics/db/queries/
  - https://docs.djangoproject.com/en/3.1/topics/db/examples/many_to_one/

## App folder
This issue pertains to the files contained in the website app folder: 
- `scope_2gzm/extracts`. 

## Tasks for `views.py`:
- [x] Create page view function `source_checkout(request, pk)`, where 'pk' is the activity id:
  - [x] Get the source
  - [x] Set source.current_user to request.user
  - [x] Return `redirect()` to url name = 'source_extract'

## Render to template
None

## Tasks for `urls.py`:
- [x] Add `source_checkout` function to list of urlpatterns:
  - URL pattern: 'source/(?P<pk>[\w]+)/checkout'
  - name: 'source_checkout'
