### ISSUE TITLE
Extracts source list page logic

### ISSUE THREAD

**Issue by karimbahgat** [wmgeolab/scope#28]
## Before you begin:
Make sure you understand how Django views work:
  - https://docs.djangoproject.com/en/3.1/topics/http/views/
  - https://docs.djangoproject.com/en/3.1/intro/tutorial03/
  
Also read up on Django urls:
  - https://docs.djangoproject.com/en/3.1/topics/http/urls/.

And understand how to read from and write to the database:
  - https://docs.djangoproject.com/en/3.1/topics/db/queries/
  - https://docs.djangoproject.com/en/3.1/topics/db/examples/many_to_one/

## App folder
This issue pertains to the files contained in the website app folder: 
- `scope_2gzm/extracts`. 

## Tasks for `views.py`:
- [x] Create page view function `source_list()`:
  - [x] Get all sources that are not checked out (`current_user` = None).
  - [x] Render to template.

## Render to template
- Path to template file: `templates/extracts/source_list.html`
- Context variables:
  - `sources` (type: QuerySet)
     Queryset of all sources not currently checked out by a user. 

## Tasks for `urls.py`:
- [x] Add `source_list` to list of urlpatterns:
  - URL pattern: 'source/list'
  - name: 'source_list'

**Comment by rrrrli** [comment]
Little bit confused about the url.py changes, can you clarify what needs to be done?

**Comment by karimbahgat** [comment]
Hey, sure. First, I assume you have read over https://docs.djangoproject.com/en/3.1/topics/http/urls/ for a basic understanding of urls.py works and how to connect views to url paths. 

Looking at what's already in `modExtracts/urls.py`, you can already see an entry in `urlpatterns` that goes `re_path('^$', views.home, name='extracts_home'),`. You need to add another urlpattern where the first arg is the URL pattern `'^source/list$'`, the second arg is a reference to the view function `views.source_list` from the views.py module, and the third name arg is `source_list`.
