### ISSUE TITLE
Extracts source list page rendering

### ISSUE THREAD

**Issue by karimbahgat** [wmgeolab/scope#29]
## Before you begin:
Make sure you understand how Django templates work:
  - https://docs.djangoproject.com/en/3.1/topics/templates/.
  - https://docs.djangoproject.com/en/3.1/ref/templates/language/
  - https://docs.djangoproject.com/en/3.1/ref/templates/builtins/
  
If the issue involves user input forms, also read up on Django forms:
  - https://docs.djangoproject.com/en/3.1/topics/forms/
  - https://docs.djangoproject.com/en/3.1/ref/forms/fields/

## App folder
This issue pertains to the files contained in the website app folder: 
- `scope_2gzm/extracts`. 

## Tasks for `forms.py`:
None

## Template context variables:
- `sources` (type: QuerySet)
     Queryset of all Source model instances not currently checked out by a user. 

## Tasks for template html file(s):
- [x] Create file `templates/extracts/source_list.html`
  - [x] Table of all sources not currently checked out.
  - [x] Each row displays key attributes of a source.
  - [x] Each row has an 'a href' 'Checkout' button to the right linking to the url name = 'source_checkout'.

### `PAGE_NAME.html`
```
{% extends "templates/base.html" %}
{% load static %}

{% block page_content %}

PAGE CONTENT GOES HERE

{% endblock %}
```
