### ISSUE TITLE
Extracts source extraction page logic

### ISSUE THREAD

**Issue by karimbahgat** [wmgeolab/scope#30]
## Before you begin:
Make sure you understand how Django views work:
  - https://docs.djangoproject.com/en/3.1/topics/http/views/
  - https://docs.djangoproject.com/en/3.1/intro/tutorial03/
  
Also read up on Django urls:
  - https://docs.djangoproject.com/en/3.1/topics/http/urls/.

And understand how to read from and write to the database:
  - https://docs.djangoproject.com/en/3.1/topics/db/queries/
  - https://docs.djangoproject.com/en/3.1/topics/db/examples/many_to_one/

NEW! Read about formsets and model formsets: 
  - [x] https://docs.djangoproject.com/en/3.1/topics/forms/formsets/
  - [x] https://docs.djangoproject.com/en/3.1/topics/forms/modelforms/#model-formsets

## App folder
This issue pertains to the files contained in the website app folder: 
- `scope_2gzm/extracts`. 

## Tasks for `views.py`:
- [x] Create page view function `source_extraction(request, pk)` where pk is the unique source identifier:
  - [x] If method = GET
    - [x] Get the source.
    - [x] Get all extracts related to that source (`source.extracts`). 
    - [x] Create ExtractFormSet pre-populated with the existing extracts.
    - [x] Render to template.
  - [x] If method = POST
    - [x] Create ExtractFormSet from the extracts in the POST data
    - [x] Validate and save the formset
    - [x] Redirect to url name = 'source_release'

## Render to template
- Path to template file: `templates/extracts/source_extraction.html`
- Context variables:
  - `source` (type: Source)
     Source being processed for extraction.
  - `formset` (type: SourceFormSet)
     Formset of existing extracts related to that source.

## Tasks for `urls.py`:
- [x] Add `source_extraction` to list of urlpatterns:
  - URL pattern: 'source/(?P<pk>[\w]+)/extraction'
  - name: 'source_extraction'
