### ISSUE TITLE
Extracts source release page redirect

### ISSUE THREAD

**Issue by karimbahgat** [wmgeolab/scope#32]
## Before you begin:
Make sure you understand how Django views work:
  - https://docs.djangoproject.com/en/3.1/topics/http/views/
  - https://docs.djangoproject.com/en/3.1/intro/tutorial03/
  
Also read up on Django urls:
  - https://docs.djangoproject.com/en/3.1/topics/http/urls/.

And understand how to read from and write to the database:
  - https://docs.djangoproject.com/en/3.1/topics/db/queries/
  - https://docs.djangoproject.com/en/3.1/topics/db/examples/many_to_one/

## App folder
This issue pertains to the files contained in the website app folder: 
- `scope_2gzm/sources`. 

## Tasks for `views.py`:
- [x] Create page view function `source_release(request, pk)`:
  - [x] Get the source. 
  - [x] Set source.current_user to None. 
  - [x] Return `redirect` to url name = `source_extract'. 

## Render to template
None

## Tasks for `urls.py`:
- [x] Add `source_release` to list of urlpatterns:
  - URL pattern: 'source/(?P[\w]+)/release'
  - name: 'source_release'

**Comment by karimbahgat** [comment]
Wrote up the issue, should be ready now.
