### ISSUE TITLE
User landing page - Start or Continue (html rendering)

### ISSUE THREAD

**Issue by karimbahgat** [wmgeolab/scope#9]
## Before you begin:
Make sure you understand how Django templates work:
  - [x] https://docs.djangoproject.com/en/3.1/topics/templates/.
  - [x] https://docs.djangoproject.com/en/3.1/ref/templates/language/
  - [x] https://docs.djangoproject.com/en/3.1/ref/templates/builtins/

If the issue involves user input forms, also read up on Django forms:
  - [x] https://docs.djangoproject.com/en/3.1/topics/forms/
  - [x] https://docs.djangoproject.com/en/3.1/ref/forms/fields/

## Template input variables:
- `continue_event` (type: parsing.models.Activity)
   Acitivity model instance if user already has an event checked out, otherwise None

## Tasks for `forms.py`:
None

## Tasks for template html file(s):
- [x] Create file `templates/parsing/landing.html`
  - [x] Conditional link button. 
    - [x] If `continue_event`
      - Go to checked out event (url name = 'event_continue', pk = continue_event.pk)
    - [x] Else
      - Go to event selection list (url name = 'event_new')

### `landing.html`
```
{% extends "templates/base.html" %}
{% load static %}

{% block page_content %}


<div style="width:100%">

{% if continue_event %}
  <a class="btn" href="{% url 'event_continue' pk=continue_event.pk %}">
   Continue
  </a>
{% else %}
  <a class="btn" href="{% url 'event_new' %}">
   Start New
  </a>
{% endif %}

</div>


{% endblock %}
```
